package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VolActividadvoluntario generated by hbm2java
 */
public class VolActividadvoluntario  implements java.io.Serializable {


     private BigDecimal ideActivoluntario;
     private String descripcion;
     private String usucreacion;
     private Date fecCreacion;
     private Set volActivoluntDets = new HashSet(0);

    public VolActividadvoluntario() {
    }

	
    public VolActividadvoluntario(BigDecimal ideActivoluntario) {
        this.ideActivoluntario = ideActivoluntario;
    }
    public VolActividadvoluntario(BigDecimal ideActivoluntario, String descripcion, String usucreacion, Date fecCreacion, Set volActivoluntDets) {
       this.ideActivoluntario = ideActivoluntario;
       this.descripcion = descripcion;
       this.usucreacion = usucreacion;
       this.fecCreacion = fecCreacion;
       this.volActivoluntDets = volActivoluntDets;
    }
   
    public BigDecimal getIdeActivoluntario() {
        return this.ideActivoluntario;
    }
    
    public void setIdeActivoluntario(BigDecimal ideActivoluntario) {
        this.ideActivoluntario = ideActivoluntario;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUsucreacion() {
        return this.usucreacion;
    }
    
    public void setUsucreacion(String usucreacion) {
        this.usucreacion = usucreacion;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public Set getVolActivoluntDets() {
        return this.volActivoluntDets;
    }
    
    public void setVolActivoluntDets(Set volActivoluntDets) {
        this.volActivoluntDets = volActivoluntDets;
    }




}


