package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolActifisica generated by hbm2java
 */
public class VolActifisica  implements java.io.Serializable {


     private BigDecimal ideActividadfisica;
     private VolVoluntario volVoluntario;
     private String tipo;
     private BigDecimal intensidadsemanal;
     private BigDecimal tiempopractica;
     private Date fecRegistro;

    public VolActifisica() {
    }

	
    public VolActifisica(BigDecimal ideActividadfisica) {
        this.ideActividadfisica = ideActividadfisica;
    }
    public VolActifisica(BigDecimal ideActividadfisica, VolVoluntario volVoluntario, String tipo, BigDecimal intensidadsemanal, BigDecimal tiempopractica, Date fecRegistro) {
       this.ideActividadfisica = ideActividadfisica;
       this.volVoluntario = volVoluntario;
       this.tipo = tipo;
       this.intensidadsemanal = intensidadsemanal;
       this.tiempopractica = tiempopractica;
       this.fecRegistro = fecRegistro;
    }
   
    public BigDecimal getIdeActividadfisica() {
        return this.ideActividadfisica;
    }
    
    public void setIdeActividadfisica(BigDecimal ideActividadfisica) {
        this.ideActividadfisica = ideActividadfisica;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public BigDecimal getIntensidadsemanal() {
        return this.intensidadsemanal;
    }
    
    public void setIntensidadsemanal(BigDecimal intensidadsemanal) {
        this.intensidadsemanal = intensidadsemanal;
    }
    public BigDecimal getTiempopractica() {
        return this.tiempopractica;
    }
    
    public void setTiempopractica(BigDecimal tiempopractica) {
        this.tiempopractica = tiempopractica;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }




}


