package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * VolActivoluntDet generated by hbm2java
 */
public class VolActivoluntDet  implements java.io.Serializable {


     private VolActivoluntDetId id;
     private VolVoluntario volVoluntario;
     private VolActividadvoluntario volActividadvoluntario;
     private String rutacertificado;
     private Date fecAprobacion;
     private String usuaprobo;
     private Character indEstadoaprobado;

    public VolActivoluntDet() {
    }

	
    public VolActivoluntDet(VolActivoluntDetId id, VolVoluntario volVoluntario, VolActividadvoluntario volActividadvoluntario) {
        this.id = id;
        this.volVoluntario = volVoluntario;
        this.volActividadvoluntario = volActividadvoluntario;
    }
    public VolActivoluntDet(VolActivoluntDetId id, VolVoluntario volVoluntario, VolActividadvoluntario volActividadvoluntario, String rutacertificado, Date fecAprobacion, String usuaprobo, Character indEstadoaprobado) {
       this.id = id;
       this.volVoluntario = volVoluntario;
       this.volActividadvoluntario = volActividadvoluntario;
       this.rutacertificado = rutacertificado;
       this.fecAprobacion = fecAprobacion;
       this.usuaprobo = usuaprobo;
       this.indEstadoaprobado = indEstadoaprobado;
    }
   
    public VolActivoluntDetId getId() {
        return this.id;
    }
    
    public void setId(VolActivoluntDetId id) {
        this.id = id;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public VolActividadvoluntario getVolActividadvoluntario() {
        return this.volActividadvoluntario;
    }
    
    public void setVolActividadvoluntario(VolActividadvoluntario volActividadvoluntario) {
        this.volActividadvoluntario = volActividadvoluntario;
    }
    public String getRutacertificado() {
        return this.rutacertificado;
    }
    
    public void setRutacertificado(String rutacertificado) {
        this.rutacertificado = rutacertificado;
    }
    public Date getFecAprobacion() {
        return this.fecAprobacion;
    }
    
    public void setFecAprobacion(Date fecAprobacion) {
        this.fecAprobacion = fecAprobacion;
    }
    public String getUsuaprobo() {
        return this.usuaprobo;
    }
    
    public void setUsuaprobo(String usuaprobo) {
        this.usuaprobo = usuaprobo;
    }
    public Character getIndEstadoaprobado() {
        return this.indEstadoaprobado;
    }
    
    public void setIndEstadoaprobado(Character indEstadoaprobado) {
        this.indEstadoaprobado = indEstadoaprobado;
    }




}


