package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VolActivoluntDetId generated by hbm2java
 */
public class VolActivoluntDetId  implements java.io.Serializable {


     private BigDecimal ideActivoluntario;
     private BigDecimal ideVoluntario;

    public VolActivoluntDetId() {
    }

    public VolActivoluntDetId(BigDecimal ideActivoluntario, BigDecimal ideVoluntario) {
       this.ideActivoluntario = ideActivoluntario;
       this.ideVoluntario = ideVoluntario;
    }
   
    public BigDecimal getIdeActivoluntario() {
        return this.ideActivoluntario;
    }
    
    public void setIdeActivoluntario(BigDecimal ideActivoluntario) {
        this.ideActivoluntario = ideActivoluntario;
    }
    public BigDecimal getIdeVoluntario() {
        return this.ideVoluntario;
    }
    
    public void setIdeVoluntario(BigDecimal ideVoluntario) {
        this.ideVoluntario = ideVoluntario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VolActivoluntDetId) ) return false;
		 VolActivoluntDetId castOther = ( VolActivoluntDetId ) other; 
         
		 return ( (this.getIdeActivoluntario()==castOther.getIdeActivoluntario()) || ( this.getIdeActivoluntario()!=null && castOther.getIdeActivoluntario()!=null && this.getIdeActivoluntario().equals(castOther.getIdeActivoluntario()) ) )
 && ( (this.getIdeVoluntario()==castOther.getIdeVoluntario()) || ( this.getIdeVoluntario()!=null && castOther.getIdeVoluntario()!=null && this.getIdeVoluntario().equals(castOther.getIdeVoluntario()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdeActivoluntario() == null ? 0 : this.getIdeActivoluntario().hashCode() );
         result = 37 * result + ( getIdeVoluntario() == null ? 0 : this.getIdeVoluntario().hashCode() );
         return result;
   }   


}


