package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolCapacitacion generated by hbm2java
 */
public class VolCapacitacion  implements java.io.Serializable {


     private BigDecimal ideCapacitacion;
     private VolVoluntario volVoluntario;
     private String curso;
     private BigDecimal ideInstitucion;
     private Date fecInicio;
     private BigDecimal horas;
     private Date fecRegistro;

    public VolCapacitacion() {
    }

	
    public VolCapacitacion(BigDecimal ideCapacitacion) {
        this.ideCapacitacion = ideCapacitacion;
    }
    public VolCapacitacion(BigDecimal ideCapacitacion, VolVoluntario volVoluntario, String curso, BigDecimal ideInstitucion, Date fecInicio, BigDecimal horas, Date fecRegistro) {
       this.ideCapacitacion = ideCapacitacion;
       this.volVoluntario = volVoluntario;
       this.curso = curso;
       this.ideInstitucion = ideInstitucion;
       this.fecInicio = fecInicio;
       this.horas = horas;
       this.fecRegistro = fecRegistro;
    }
   
    public BigDecimal getIdeCapacitacion() {
        return this.ideCapacitacion;
    }
    
    public void setIdeCapacitacion(BigDecimal ideCapacitacion) {
        this.ideCapacitacion = ideCapacitacion;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public String getCurso() {
        return this.curso;
    }
    
    public void setCurso(String curso) {
        this.curso = curso;
    }
    public BigDecimal getIdeInstitucion() {
        return this.ideInstitucion;
    }
    
    public void setIdeInstitucion(BigDecimal ideInstitucion) {
        this.ideInstitucion = ideInstitucion;
    }
    public Date getFecInicio() {
        return this.fecInicio;
    }
    
    public void setFecInicio(Date fecInicio) {
        this.fecInicio = fecInicio;
    }
    public BigDecimal getHoras() {
        return this.horas;
    }
    
    public void setHoras(BigDecimal horas) {
        this.horas = horas;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }




}


