package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolCerificacion generated by hbm2java
 */
public class VolCerificacion  implements java.io.Serializable {


     private BigDecimal ideCertificacion;
     private VolVoluntario volVoluntario;
     private String rutacertificacion;
     private Date fecRegistro;

    public VolCerificacion() {
    }

	
    public VolCerificacion(BigDecimal ideCertificacion) {
        this.ideCertificacion = ideCertificacion;
    }
    public VolCerificacion(BigDecimal ideCertificacion, VolVoluntario volVoluntario, String rutacertificacion, Date fecRegistro) {
       this.ideCertificacion = ideCertificacion;
       this.volVoluntario = volVoluntario;
       this.rutacertificacion = rutacertificacion;
       this.fecRegistro = fecRegistro;
    }
   
    public BigDecimal getIdeCertificacion() {
        return this.ideCertificacion;
    }
    
    public void setIdeCertificacion(BigDecimal ideCertificacion) {
        this.ideCertificacion = ideCertificacion;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public String getRutacertificacion() {
        return this.rutacertificacion;
    }
    
    public void setRutacertificacion(String rutacertificacion) {
        this.rutacertificacion = rutacertificacion;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }




}


