package com.tismart.voluntariado.bean;
// Generated 22-feb-2016 14:53:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VolDistrito generated by hbm2java
 */
public class VolDistrito  implements java.io.Serializable {


     private BigDecimal codDistrito;
     private VolProvincia volProvincia;
     private String nombredis;
     private Set volVoluntarios = new HashSet(0);

    public VolDistrito() {
    }

	
    public VolDistrito(BigDecimal codDistrito) {
        this.codDistrito = codDistrito;
    }
    public VolDistrito(BigDecimal codDistrito, VolProvincia volProvincia, String nombredis, Set volVoluntarios) {
       this.codDistrito = codDistrito;
       this.volProvincia = volProvincia;
       this.nombredis = nombredis;
       this.volVoluntarios = volVoluntarios;
    }
   
    public BigDecimal getCodDistrito() {
        return this.codDistrito;
    }
    
    public void setCodDistrito(BigDecimal codDistrito) {
        this.codDistrito = codDistrito;
    }
    public VolProvincia getVolProvincia() {
        return this.volProvincia;
    }
    
    public void setVolProvincia(VolProvincia volProvincia) {
        this.volProvincia = volProvincia;
    }
    public String getNombredis() {
        return this.nombredis;
    }
    
    public void setNombredis(String nombredis) {
        this.nombredis = nombredis;
    }
    public Set getVolVoluntarios() {
        return this.volVoluntarios;
    }
    
    public void setVolVoluntarios(Set volVoluntarios) {
        this.volVoluntarios = volVoluntarios;
    }




}


