package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VolDepartamento generated by hbm2java
 */
public class VolDepartamento  implements java.io.Serializable {


     private BigDecimal codDepartamento;
     private VolPais volPais;
     private String nombredep;
     private Set volVolusespads = new HashSet(0);
     private Set volUsuarios = new HashSet(0);
     private Set volProvincias = new HashSet(0);
     private Set volVoluntarios = new HashSet(0);

    public VolDepartamento() {
    }

	
    public VolDepartamento(BigDecimal codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public VolDepartamento(BigDecimal codDepartamento, VolPais volPais, String nombredep, Set volVolusespads, Set volUsuarios, Set volProvincias, Set volVoluntarios) {
       this.codDepartamento = codDepartamento;
       this.volPais = volPais;
       this.nombredep = nombredep;
       this.volVolusespads = volVolusespads;
       this.volUsuarios = volUsuarios;
       this.volProvincias = volProvincias;
       this.volVoluntarios = volVoluntarios;
    }
   
    public BigDecimal getCodDepartamento() {
        return this.codDepartamento;
    }
    
    public void setCodDepartamento(BigDecimal codDepartamento) {
        this.codDepartamento = codDepartamento;
    }
    public VolPais getVolPais() {
        return this.volPais;
    }
    
    public void setVolPais(VolPais volPais) {
        this.volPais = volPais;
    }
    public String getNombredep() {
        return this.nombredep;
    }
    
    public void setNombredep(String nombredep) {
        this.nombredep = nombredep;
    }
    public Set getVolVolusespads() {
        return this.volVolusespads;
    }
    
    public void setVolVolusespads(Set volVolusespads) {
        this.volVolusespads = volVolusespads;
    }
    public Set getVolUsuarios() {
        return this.volUsuarios;
    }
    
    public void setVolUsuarios(Set volUsuarios) {
        this.volUsuarios = volUsuarios;
    }
    public Set getVolProvincias() {
        return this.volProvincias;
    }
    
    public void setVolProvincias(Set volProvincias) {
        this.volProvincias = volProvincias;
    }
    public Set getVolVoluntarios() {
        return this.volVoluntarios;
    }
    
    public void setVolVoluntarios(Set volVoluntarios) {
        this.volVoluntarios = volVoluntarios;
    }




}


