package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * VolEvenvoluntDetId generated by hbm2java
 */
public class VolEvenvoluntDetId  implements java.io.Serializable {


     private BigDecimal ideVoluntario;
     private BigDecimal ideEvento;

    public VolEvenvoluntDetId() {
    }

    public VolEvenvoluntDetId(BigDecimal ideVoluntario, BigDecimal ideEvento) {
       this.ideVoluntario = ideVoluntario;
       this.ideEvento = ideEvento;
    }
   
    public BigDecimal getIdeVoluntario() {
        return this.ideVoluntario;
    }
    
    public void setIdeVoluntario(BigDecimal ideVoluntario) {
        this.ideVoluntario = ideVoluntario;
    }
    public BigDecimal getIdeEvento() {
        return this.ideEvento;
    }
    
    public void setIdeEvento(BigDecimal ideEvento) {
        this.ideEvento = ideEvento;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof VolEvenvoluntDetId) ) return false;
		 VolEvenvoluntDetId castOther = ( VolEvenvoluntDetId ) other; 
         
		 return ( (this.getIdeVoluntario()==castOther.getIdeVoluntario()) || ( this.getIdeVoluntario()!=null && castOther.getIdeVoluntario()!=null && this.getIdeVoluntario().equals(castOther.getIdeVoluntario()) ) )
 && ( (this.getIdeEvento()==castOther.getIdeEvento()) || ( this.getIdeEvento()!=null && castOther.getIdeEvento()!=null && this.getIdeEvento().equals(castOther.getIdeEvento()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdeVoluntario() == null ? 0 : this.getIdeVoluntario().hashCode() );
         result = 37 * result + ( getIdeEvento() == null ? 0 : this.getIdeEvento().hashCode() );
         return result;
   }   


}


