package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolEspecialidad generated by hbm2java
 */
public class VolEspecialidad  implements java.io.Serializable {


     private BigDecimal ideEspecialidad;
     private VolVoluntario volVoluntario;
     private String institucion;
     private BigDecimal aniofinalizacion;
     private Date fecRegistro;

    public VolEspecialidad() {
    }

	
    public VolEspecialidad(BigDecimal ideEspecialidad) {
        this.ideEspecialidad = ideEspecialidad;
    }
    public VolEspecialidad(BigDecimal ideEspecialidad, VolVoluntario volVoluntario, String institucion, BigDecimal aniofinalizacion, Date fecRegistro) {
       this.ideEspecialidad = ideEspecialidad;
       this.volVoluntario = volVoluntario;
       this.institucion = institucion;
       this.aniofinalizacion = aniofinalizacion;
       this.fecRegistro = fecRegistro;
    }
   
    public BigDecimal getIdeEspecialidad() {
        return this.ideEspecialidad;
    }
    
    public void setIdeEspecialidad(BigDecimal ideEspecialidad) {
        this.ideEspecialidad = ideEspecialidad;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public String getInstitucion() {
        return this.institucion;
    }
    
    public void setInstitucion(String institucion) {
        this.institucion = institucion;
    }
    public BigDecimal getAniofinalizacion() {
        return this.aniofinalizacion;
    }
    
    public void setAniofinalizacion(BigDecimal aniofinalizacion) {
        this.aniofinalizacion = aniofinalizacion;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }




}


