package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1



/**
 * VolEvenvoluntDet generated by hbm2java
 */
public class VolEvenvoluntDet  implements java.io.Serializable {


     private VolEvenvoluntDetId id;
     private VolVoluntario volVoluntario;
     private VolEvento volEvento;
     private String rutavacunas;
     private Character indConformidadvacuna;

    public VolEvenvoluntDet() {
    }

	
    public VolEvenvoluntDet(VolEvenvoluntDetId id, VolVoluntario volVoluntario, VolEvento volEvento) {
        this.id = id;
        this.volVoluntario = volVoluntario;
        this.volEvento = volEvento;
    }
    public VolEvenvoluntDet(VolEvenvoluntDetId id, VolVoluntario volVoluntario, VolEvento volEvento, String rutavacunas, Character indConformidadvacuna) {
       this.id = id;
       this.volVoluntario = volVoluntario;
       this.volEvento = volEvento;
       this.rutavacunas = rutavacunas;
       this.indConformidadvacuna = indConformidadvacuna;
    }
   
    public VolEvenvoluntDetId getId() {
        return this.id;
    }
    
    public void setId(VolEvenvoluntDetId id) {
        this.id = id;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public VolEvento getVolEvento() {
        return this.volEvento;
    }
    
    public void setVolEvento(VolEvento volEvento) {
        this.volEvento = volEvento;
    }
    public String getRutavacunas() {
        return this.rutavacunas;
    }
    
    public void setRutavacunas(String rutavacunas) {
        this.rutavacunas = rutavacunas;
    }
    public Character getIndConformidadvacuna() {
        return this.indConformidadvacuna;
    }
    
    public void setIndConformidadvacuna(Character indConformidadvacuna) {
        this.indConformidadvacuna = indConformidadvacuna;
    }




}


