package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolEspecialidad generated by hbm2java
 */
public class VolEspecialidad  implements java.io.Serializable {


     private BigDecimal ideEspecialidad;
     private VolVoluntario volVoluntario;
     private BigDecimal ideInstitucion;
     private BigDecimal aniofinalizacion;
     private Date fecRegistro;

    public VolEspecialidad() {
    }

	
    public VolEspecialidad(BigDecimal ideEspecialidad) {
        this.ideEspecialidad = ideEspecialidad;
    }
    public VolEspecialidad(BigDecimal ideEspecialidad, VolVoluntario volVoluntario, BigDecimal ideInstitucion, BigDecimal aniofinalizacion, Date fecRegistro) {
       this.ideEspecialidad = ideEspecialidad;
       this.volVoluntario = volVoluntario;
       this.ideInstitucion = ideInstitucion;
       this.aniofinalizacion = aniofinalizacion;
       this.fecRegistro = fecRegistro;
    }
   
    public BigDecimal getIdeEspecialidad() {
        return this.ideEspecialidad;
    }
    
    public void setIdeEspecialidad(BigDecimal ideEspecialidad) {
        this.ideEspecialidad = ideEspecialidad;
    }
    public VolVoluntario getVolVoluntario() {
        return this.volVoluntario;
    }
    
    public void setVolVoluntario(VolVoluntario volVoluntario) {
        this.volVoluntario = volVoluntario;
    }
    public BigDecimal getIdeInstitucion() {
        return this.ideInstitucion;
    }
    
    public void setIdeInstitucion(BigDecimal ideInstitucion) {
        this.ideInstitucion = ideInstitucion;
    }
    public BigDecimal getAniofinalizacion() {
        return this.aniofinalizacion;
    }
    
    public void setAniofinalizacion(BigDecimal aniofinalizacion) {
        this.aniofinalizacion = aniofinalizacion;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }




}


