package com.tismart.voluntariado.bean;
// Generated 23-feb-2016 11:38:34 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VolGrupo generated by hbm2java
 */
public class VolGrupo  implements java.io.Serializable {


     private BigDecimal ideGrupo;
     private Date fecRegistro;
     private String nombre;
     private String direccion;
     private String telefono;
     private String representante;
     private String descripcion;
     private Set volVoluntarios = new HashSet(0);

    public VolGrupo() {
    }

	
    public VolGrupo(BigDecimal ideGrupo) {
        this.ideGrupo = ideGrupo;
    }
    public VolGrupo(BigDecimal ideGrupo, Date fecRegistro, String nombre, String direccion, String telefono, String representante, String descripcion, Set volVoluntarios) {
       this.ideGrupo = ideGrupo;
       this.fecRegistro = fecRegistro;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.representante = representante;
       this.descripcion = descripcion;
       this.volVoluntarios = volVoluntarios;
    }
   
    public BigDecimal getIdeGrupo() {
        return this.ideGrupo;
    }
    
    public void setIdeGrupo(BigDecimal ideGrupo) {
        this.ideGrupo = ideGrupo;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getRepresentante() {
        return this.representante;
    }
    
    public void setRepresentante(String representante) {
        this.representante = representante;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getVolVoluntarios() {
        return this.volVoluntarios;
    }
    
    public void setVolVoluntarios(Set volVoluntarios) {
        this.volVoluntarios = volVoluntarios;
    }




}


