package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VolOpcion generated by hbm2java
 */
public class VolOpcion  implements java.io.Serializable {


     private BigDecimal ideOpcion;
     private String modulo;
     private String enlace;
     private Set volPerfils = new HashSet(0);

    public VolOpcion() {
    }

	
    public VolOpcion(BigDecimal ideOpcion) {
        this.ideOpcion = ideOpcion;
    }
    public VolOpcion(BigDecimal ideOpcion, String modulo, String enlace, Set volPerfils) {
       this.ideOpcion = ideOpcion;
       this.modulo = modulo;
       this.enlace = enlace;
       this.volPerfils = volPerfils;
    }
   
    public BigDecimal getIdeOpcion() {
        return this.ideOpcion;
    }
    
    public void setIdeOpcion(BigDecimal ideOpcion) {
        this.ideOpcion = ideOpcion;
    }
    public String getModulo() {
        return this.modulo;
    }
    
    public void setModulo(String modulo) {
        this.modulo = modulo;
    }
    public String getEnlace() {
        return this.enlace;
    }
    
    public void setEnlace(String enlace) {
        this.enlace = enlace;
    }
    public Set getVolPerfils() {
        return this.volPerfils;
    }
    
    public void setVolPerfils(Set volPerfils) {
        this.volPerfils = volPerfils;
    }




}


