package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * VolPais generated by hbm2java
 */
public class VolPais  implements java.io.Serializable {


     private BigDecimal codPais;
     private String nombrepa;
     private Set volDepartamentos = new HashSet(0);
     private Set volVolusespads = new HashSet(0);
     private Set volVoluntarios = new HashSet(0);

    public VolPais() {
    }

	
    public VolPais(BigDecimal codPais) {
        this.codPais = codPais;
    }
    public VolPais(BigDecimal codPais, String nombrepa, Set volDepartamentos, Set volVolusespads, Set volVoluntarios) {
       this.codPais = codPais;
       this.nombrepa = nombrepa;
       this.volDepartamentos = volDepartamentos;
       this.volVolusespads = volVolusespads;
       this.volVoluntarios = volVoluntarios;
    }
   
    public BigDecimal getCodPais() {
        return this.codPais;
    }
    
    public void setCodPais(BigDecimal codPais) {
        this.codPais = codPais;
    }
    public String getNombrepa() {
        return this.nombrepa;
    }
    
    public void setNombrepa(String nombrepa) {
        this.nombrepa = nombrepa;
    }
    public Set getVolDepartamentos() {
        return this.volDepartamentos;
    }
    
    public void setVolDepartamentos(Set volDepartamentos) {
        this.volDepartamentos = volDepartamentos;
    }
    public Set getVolVolusespads() {
        return this.volVolusespads;
    }
    
    public void setVolVolusespads(Set volVolusespads) {
        this.volVolusespads = volVolusespads;
    }
    public Set getVolVoluntarios() {
        return this.volVoluntarios;
    }
    
    public void setVolVoluntarios(Set volVoluntarios) {
        this.volVoluntarios = volVoluntarios;
    }




}


