package com.tismart.voluntariado.bean;
// Generated 24-feb-2016 11:24:26 by Hibernate Tools 4.3.1



/**
 * VolTermlegal generated by hbm2java
 */
public class VolTermlegal  implements java.io.Serializable {


     private String ideTerminolegal;
     private String descripcion;
     private String usucreacion;
     private String fecCreacion;

    public VolTermlegal() {
    }

	
    public VolTermlegal(String ideTerminolegal) {
        this.ideTerminolegal = ideTerminolegal;
    }
    public VolTermlegal(String ideTerminolegal, String descripcion, String usucreacion, String fecCreacion) {
       this.ideTerminolegal = ideTerminolegal;
       this.descripcion = descripcion;
       this.usucreacion = usucreacion;
       this.fecCreacion = fecCreacion;
    }
   
    public String getIdeTerminolegal() {
        return this.ideTerminolegal;
    }
    
    public void setIdeTerminolegal(String ideTerminolegal) {
        this.ideTerminolegal = ideTerminolegal;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUsucreacion() {
        return this.usucreacion;
    }
    
    public void setUsucreacion(String usucreacion) {
        this.usucreacion = usucreacion;
    }
    public String getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(String fecCreacion) {
        this.fecCreacion = fecCreacion;
    }




}


