package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolVacuna generated by hbm2java
 */
public class VolVacuna  implements java.io.Serializable {


     private BigDecimal ideVacuna;
     private String descripcion;
     private String usucreacion;
     private Date fecCreacion;
     private String usumodificacion;
     private Date fecModificacion;

    public VolVacuna() {
    }

	
    public VolVacuna(BigDecimal ideVacuna) {
        this.ideVacuna = ideVacuna;
    }
    public VolVacuna(BigDecimal ideVacuna, String descripcion, String usucreacion, Date fecCreacion, String usumodificacion, Date fecModificacion) {
       this.ideVacuna = ideVacuna;
       this.descripcion = descripcion;
       this.usucreacion = usucreacion;
       this.fecCreacion = fecCreacion;
       this.usumodificacion = usumodificacion;
       this.fecModificacion = fecModificacion;
    }
   
    public BigDecimal getIdeVacuna() {
        return this.ideVacuna;
    }
    
    public void setIdeVacuna(BigDecimal ideVacuna) {
        this.ideVacuna = ideVacuna;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getUsucreacion() {
        return this.usucreacion;
    }
    
    public void setUsucreacion(String usucreacion) {
        this.usucreacion = usucreacion;
    }
    public Date getFecCreacion() {
        return this.fecCreacion;
    }
    
    public void setFecCreacion(Date fecCreacion) {
        this.fecCreacion = fecCreacion;
    }
    public String getUsumodificacion() {
        return this.usumodificacion;
    }
    
    public void setUsumodificacion(String usumodificacion) {
        this.usumodificacion = usumodificacion;
    }
    public Date getFecModificacion() {
        return this.fecModificacion;
    }
    
    public void setFecModificacion(Date fecModificacion) {
        this.fecModificacion = fecModificacion;
    }




}


