package com.tismart.voluntariado.bean;
// Generated 22-feb-2016 14:53:29 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * VolVoluntario generated by hbm2java
 */
public class VolVoluntario  implements java.io.Serializable {


     private BigDecimal ideVoluntario;
     private VolTipdocum volTipdocum;
     private VolEstavolun volEstavolun;
     private VolPais volPais;
     private VolTipvolun volTipvolun;
     private VolProvincia volProvincia;
     private VolProfesion volProfesion;
     private VolGsanguineo volGsanguineo;
     private VolGradoacade volGradoacade;
     private VolDistrito volDistrito;
     private VolDepartamento volDepartamento;
     private VolGrupo volGrupo;
     private String apreciacion;
     private BigDecimal esrepresentante;
     private BigDecimal indHabilitado;
     private String nombres;
     private String apellidos;
     private String numDocumento;
     private Date fecNacimiento;
     private String rutaautorizacion;
     private String domicilio;
     private String telefono;
     private String celular;
     private String correo;
     private String cskype;
     private String motivacion;
     private Date fecRegistro;
     private Date fecValidacion;
     private Character indPertenecegrupo;
     private BigDecimal aceptaterminos;

    public VolVoluntario() {
    }

	
    public VolVoluntario(BigDecimal ideVoluntario, VolTipdocum volTipdocum, VolEstavolun volEstavolun, VolProfesion volProfesion, VolGsanguineo volGsanguineo, VolGradoacade volGradoacade, String nombres, String apellidos, String numDocumento, Date fecNacimiento, String telefono, String celular, String correo) {
        this.ideVoluntario = ideVoluntario;
        this.volTipdocum = volTipdocum;
        this.volEstavolun = volEstavolun;
        this.volProfesion = volProfesion;
        this.volGsanguineo = volGsanguineo;
        this.volGradoacade = volGradoacade;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numDocumento = numDocumento;
        this.fecNacimiento = fecNacimiento;
        this.telefono = telefono;
        this.celular = celular;
        this.correo = correo;
    }
    public VolVoluntario(BigDecimal ideVoluntario, VolTipdocum volTipdocum, VolEstavolun volEstavolun, VolPais volPais, VolTipvolun volTipvolun, VolProvincia volProvincia, VolProfesion volProfesion, VolGsanguineo volGsanguineo, VolGradoacade volGradoacade, VolDistrito volDistrito, VolDepartamento volDepartamento, VolGrupo volGrupo, String apreciacion, BigDecimal esrepresentante, BigDecimal indHabilitado, String nombres, String apellidos, String numDocumento, Date fecNacimiento, String rutaautorizacion, String domicilio, String telefono, String celular, String correo, String cskype, String motivacion, Date fecRegistro, Date fecValidacion, Character indPertenecegrupo, BigDecimal aceptaterminos) {
       this.ideVoluntario = ideVoluntario;
       this.volTipdocum = volTipdocum;
       this.volEstavolun = volEstavolun;
       this.volPais = volPais;
       this.volTipvolun = volTipvolun;
       this.volProvincia = volProvincia;
       this.volProfesion = volProfesion;
       this.volGsanguineo = volGsanguineo;
       this.volGradoacade = volGradoacade;
       this.volDistrito = volDistrito;
       this.volDepartamento = volDepartamento;
       this.volGrupo = volGrupo;
       this.apreciacion = apreciacion;
       this.esrepresentante = esrepresentante;
       this.indHabilitado = indHabilitado;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numDocumento = numDocumento;
       this.fecNacimiento = fecNacimiento;
       this.rutaautorizacion = rutaautorizacion;
       this.domicilio = domicilio;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.cskype = cskype;
       this.motivacion = motivacion;
       this.fecRegistro = fecRegistro;
       this.fecValidacion = fecValidacion;
       this.indPertenecegrupo = indPertenecegrupo;
       this.aceptaterminos = aceptaterminos;
    }
   
    public BigDecimal getIdeVoluntario() {
        return this.ideVoluntario;
    }
    
    public void setIdeVoluntario(BigDecimal ideVoluntario) {
        this.ideVoluntario = ideVoluntario;
    }
    public VolTipdocum getVolTipdocum() {
        return this.volTipdocum;
    }
    
    public void setVolTipdocum(VolTipdocum volTipdocum) {
        this.volTipdocum = volTipdocum;
    }
    public VolEstavolun getVolEstavolun() {
        return this.volEstavolun;
    }
    
    public void setVolEstavolun(VolEstavolun volEstavolun) {
        this.volEstavolun = volEstavolun;
    }
    public VolPais getVolPais() {
        return this.volPais;
    }
    
    public void setVolPais(VolPais volPais) {
        this.volPais = volPais;
    }
    public VolTipvolun getVolTipvolun() {
        return this.volTipvolun;
    }
    
    public void setVolTipvolun(VolTipvolun volTipvolun) {
        this.volTipvolun = volTipvolun;
    }
    public VolProvincia getVolProvincia() {
        return this.volProvincia;
    }
    
    public void setVolProvincia(VolProvincia volProvincia) {
        this.volProvincia = volProvincia;
    }
    public VolProfesion getVolProfesion() {
        return this.volProfesion;
    }
    
    public void setVolProfesion(VolProfesion volProfesion) {
        this.volProfesion = volProfesion;
    }
    public VolGsanguineo getVolGsanguineo() {
        return this.volGsanguineo;
    }
    
    public void setVolGsanguineo(VolGsanguineo volGsanguineo) {
        this.volGsanguineo = volGsanguineo;
    }
    public VolGradoacade getVolGradoacade() {
        return this.volGradoacade;
    }
    
    public void setVolGradoacade(VolGradoacade volGradoacade) {
        this.volGradoacade = volGradoacade;
    }
    public VolDistrito getVolDistrito() {
        return this.volDistrito;
    }
    
    public void setVolDistrito(VolDistrito volDistrito) {
        this.volDistrito = volDistrito;
    }
    public VolDepartamento getVolDepartamento() {
        return this.volDepartamento;
    }
    
    public void setVolDepartamento(VolDepartamento volDepartamento) {
        this.volDepartamento = volDepartamento;
    }
    public VolGrupo getVolGrupo() {
        return this.volGrupo;
    }
    
    public void setVolGrupo(VolGrupo volGrupo) {
        this.volGrupo = volGrupo;
    }
    public String getApreciacion() {
        return this.apreciacion;
    }
    
    public void setApreciacion(String apreciacion) {
        this.apreciacion = apreciacion;
    }
    public BigDecimal getEsrepresentante() {
        return this.esrepresentante;
    }
    
    public void setEsrepresentante(BigDecimal esrepresentante) {
        this.esrepresentante = esrepresentante;
    }
    public BigDecimal getIndHabilitado() {
        return this.indHabilitado;
    }
    
    public void setIndHabilitado(BigDecimal indHabilitado) {
        this.indHabilitado = indHabilitado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNumDocumento() {
        return this.numDocumento;
    }
    
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento;
    }
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }
    
    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }
    public String getRutaautorizacion() {
        return this.rutaautorizacion;
    }
    
    public void setRutaautorizacion(String rutaautorizacion) {
        this.rutaautorizacion = rutaautorizacion;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCskype() {
        return this.cskype;
    }
    
    public void setCskype(String cskype) {
        this.cskype = cskype;
    }
    public String getMotivacion() {
        return this.motivacion;
    }
    
    public void setMotivacion(String motivacion) {
        this.motivacion = motivacion;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public Date getFecValidacion() {
        return this.fecValidacion;
    }
    
    public void setFecValidacion(Date fecValidacion) {
        this.fecValidacion = fecValidacion;
    }
    public Character getIndPertenecegrupo() {
        return this.indPertenecegrupo;
    }
    
    public void setIndPertenecegrupo(Character indPertenecegrupo) {
        this.indPertenecegrupo = indPertenecegrupo;
    }
    public BigDecimal getAceptaterminos() {
        return this.aceptaterminos;
    }
    
    public void setAceptaterminos(BigDecimal aceptaterminos) {
        this.aceptaterminos = aceptaterminos;
    }




}


