package com.tismart.voluntariado.bean;
// Generated 26-feb-2016 9:56:41 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VolVoluntario generated by hbm2java
 */
public class VolVoluntario  implements java.io.Serializable {


     private BigDecimal ideVoluntario;
     private VolTipdocum volTipdocum;
     private VolEstavolun volEstavolun;
     private VolPais volPais;
     private VolDepartamento volDepartamento;
     private VolProvincia volProvincia;
     private VolDistrito volDistrito;
     private VolGradoacade volGradoacade;
     private VolGsanguineo volGsanguineo;
     private VolProfesion volProfesion;
     private VolTipvolun volTipvolun;
     private String apreciacion;
     private BigDecimal esrepresentante;
     private BigDecimal indHabilitado;
     private String nombres;
     private String apellidos;
     private String numDocumento;
     private Date fecNacimiento;
     private String rutaautorizacion;
     private String domicilio;
     private String telefono;
     private String celular;
     private String correo;
     private String cskype;
     private String motivacion;
     private Date fecRegistro;
     private Date fecValidacion;
     private Character indPertenecegrupo;
     private BigDecimal ideGrupo;
     private BigDecimal aceptaterminos;
     private Set volEvenvoluntDets = new HashSet(0);
     private Set volCapacitacions = new HashSet(0);
     private Set volEspecialidads = new HashSet(0);
     private Set volActivoluntDets = new HashSet(0);
     private Set volConfirmacions = new HashSet(0);
     private Set volCerificacions = new HashSet(0);

    public VolVoluntario() {
    }

	
    public VolVoluntario(BigDecimal ideVoluntario, VolTipdocum volTipdocum, VolEstavolun volEstavolun, VolGradoacade volGradoacade, VolGsanguineo volGsanguineo, VolProfesion volProfesion, String nombres, String apellidos, String numDocumento, Date fecNacimiento, String telefono, String celular, String correo) {
        this.ideVoluntario = ideVoluntario;
        this.volTipdocum = volTipdocum;
        this.volEstavolun = volEstavolun;
        this.volGradoacade = volGradoacade;
        this.volGsanguineo = volGsanguineo;
        this.volProfesion = volProfesion;
        this.nombres = nombres;
        this.apellidos = apellidos;
        this.numDocumento = numDocumento;
        this.fecNacimiento = fecNacimiento;
        this.telefono = telefono;
        this.celular = celular;
        this.correo = correo;
    }
    public VolVoluntario(BigDecimal ideVoluntario, VolTipdocum volTipdocum, VolEstavolun volEstavolun, VolPais volPais, VolDepartamento volDepartamento, VolProvincia volProvincia, VolDistrito volDistrito, VolGradoacade volGradoacade, VolGsanguineo volGsanguineo, VolProfesion volProfesion, VolTipvolun volTipvolun, String apreciacion, BigDecimal esrepresentante, BigDecimal indHabilitado, String nombres, String apellidos, String numDocumento, Date fecNacimiento, String rutaautorizacion, String domicilio, String telefono, String celular, String correo, String cskype, String motivacion, Date fecRegistro, Date fecValidacion, Character indPertenecegrupo, BigDecimal ideGrupo, BigDecimal aceptaterminos, Set volEvenvoluntDets, Set volCapacitacions, Set volEspecialidads, Set volActivoluntDets, Set volConfirmacions, Set volCerificacions) {
       this.ideVoluntario = ideVoluntario;
       this.volTipdocum = volTipdocum;
       this.volEstavolun = volEstavolun;
       this.volPais = volPais;
       this.volDepartamento = volDepartamento;
       this.volProvincia = volProvincia;
       this.volDistrito = volDistrito;
       this.volGradoacade = volGradoacade;
       this.volGsanguineo = volGsanguineo;
       this.volProfesion = volProfesion;
       this.volTipvolun = volTipvolun;
       this.apreciacion = apreciacion;
       this.esrepresentante = esrepresentante;
       this.indHabilitado = indHabilitado;
       this.nombres = nombres;
       this.apellidos = apellidos;
       this.numDocumento = numDocumento;
       this.fecNacimiento = fecNacimiento;
       this.rutaautorizacion = rutaautorizacion;
       this.domicilio = domicilio;
       this.telefono = telefono;
       this.celular = celular;
       this.correo = correo;
       this.cskype = cskype;
       this.motivacion = motivacion;
       this.fecRegistro = fecRegistro;
       this.fecValidacion = fecValidacion;
       this.indPertenecegrupo = indPertenecegrupo;
       this.ideGrupo = ideGrupo;
       this.aceptaterminos = aceptaterminos;
       this.volEvenvoluntDets = volEvenvoluntDets;
       this.volCapacitacions = volCapacitacions;
       this.volEspecialidads = volEspecialidads;
       this.volActivoluntDets = volActivoluntDets;
       this.volConfirmacions = volConfirmacions;
       this.volCerificacions = volCerificacions;
    }
   
    public BigDecimal getIdeVoluntario() {
        return this.ideVoluntario;
    }
    
    public void setIdeVoluntario(BigDecimal ideVoluntario) {
        this.ideVoluntario = ideVoluntario;
    }
    public VolTipdocum getVolTipdocum() {
        return this.volTipdocum;
    }
    
    public void setVolTipdocum(VolTipdocum volTipdocum) {
        this.volTipdocum = volTipdocum;
    }
    public VolEstavolun getVolEstavolun() {
        return this.volEstavolun;
    }
    
    public void setVolEstavolun(VolEstavolun volEstavolun) {
        this.volEstavolun = volEstavolun;
    }
    public VolPais getVolPais() {
        return this.volPais;
    }
    
    public void setVolPais(VolPais volPais) {
        this.volPais = volPais;
    }
    public VolDepartamento getVolDepartamento() {
        return this.volDepartamento;
    }
    
    public void setVolDepartamento(VolDepartamento volDepartamento) {
        this.volDepartamento = volDepartamento;
    }
    public VolProvincia getVolProvincia() {
        return this.volProvincia;
    }
    
    public void setVolProvincia(VolProvincia volProvincia) {
        this.volProvincia = volProvincia;
    }
    public VolDistrito getVolDistrito() {
        return this.volDistrito;
    }
    
    public void setVolDistrito(VolDistrito volDistrito) {
        this.volDistrito = volDistrito;
    }
    public VolGradoacade getVolGradoacade() {
        return this.volGradoacade;
    }
    
    public void setVolGradoacade(VolGradoacade volGradoacade) {
        this.volGradoacade = volGradoacade;
    }
    public VolGsanguineo getVolGsanguineo() {
        return this.volGsanguineo;
    }
    
    public void setVolGsanguineo(VolGsanguineo volGsanguineo) {
        this.volGsanguineo = volGsanguineo;
    }
    public VolProfesion getVolProfesion() {
        return this.volProfesion;
    }
    
    public void setVolProfesion(VolProfesion volProfesion) {
        this.volProfesion = volProfesion;
    }
    public VolTipvolun getVolTipvolun() {
        return this.volTipvolun;
    }
    
    public void setVolTipvolun(VolTipvolun volTipvolun) {
        this.volTipvolun = volTipvolun;
    }
    public String getApreciacion() {
        return this.apreciacion;
    }
    
    public void setApreciacion(String apreciacion) {
        this.apreciacion = apreciacion;
    }
    public BigDecimal getEsrepresentante() {
        return this.esrepresentante;
    }
    
    public void setEsrepresentante(BigDecimal esrepresentante) {
        this.esrepresentante = esrepresentante;
    }
    public BigDecimal getIndHabilitado() {
        return this.indHabilitado;
    }
    
    public void setIndHabilitado(BigDecimal indHabilitado) {
        this.indHabilitado = indHabilitado;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getNumDocumento() {
        return this.numDocumento;
    }
    
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento;
    }
    public Date getFecNacimiento() {
        return this.fecNacimiento;
    }
    
    public void setFecNacimiento(Date fecNacimiento) {
        this.fecNacimiento = fecNacimiento;
    }
    public String getRutaautorizacion() {
        return this.rutaautorizacion;
    }
    
    public void setRutaautorizacion(String rutaautorizacion) {
        this.rutaautorizacion = rutaautorizacion;
    }
    public String getDomicilio() {
        return this.domicilio;
    }
    
    public void setDomicilio(String domicilio) {
        this.domicilio = domicilio;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getCskype() {
        return this.cskype;
    }
    
    public void setCskype(String cskype) {
        this.cskype = cskype;
    }
    public String getMotivacion() {
        return this.motivacion;
    }
    
    public void setMotivacion(String motivacion) {
        this.motivacion = motivacion;
    }
    public Date getFecRegistro() {
        return this.fecRegistro;
    }
    
    public void setFecRegistro(Date fecRegistro) {
        this.fecRegistro = fecRegistro;
    }
    public Date getFecValidacion() {
        return this.fecValidacion;
    }
    
    public void setFecValidacion(Date fecValidacion) {
        this.fecValidacion = fecValidacion;
    }
    public Character getIndPertenecegrupo() {
        return this.indPertenecegrupo;
    }
    
    public void setIndPertenecegrupo(Character indPertenecegrupo) {
        this.indPertenecegrupo = indPertenecegrupo;
    }
    public BigDecimal getIdeGrupo() {
        return this.ideGrupo;
    }
    
    public void setIdeGrupo(BigDecimal ideGrupo) {
        this.ideGrupo = ideGrupo;
    }
    public BigDecimal getAceptaterminos() {
        return this.aceptaterminos;
    }
    
    public void setAceptaterminos(BigDecimal aceptaterminos) {
        this.aceptaterminos = aceptaterminos;
    }
    public Set getVolEvenvoluntDets() {
        return this.volEvenvoluntDets;
    }
    
    public void setVolEvenvoluntDets(Set volEvenvoluntDets) {
        this.volEvenvoluntDets = volEvenvoluntDets;
    }
    public Set getVolCapacitacions() {
        return this.volCapacitacions;
    }
    
    public void setVolCapacitacions(Set volCapacitacions) {
        this.volCapacitacions = volCapacitacions;
    }
    public Set getVolEspecialidads() {
        return this.volEspecialidads;
    }
    
    public void setVolEspecialidads(Set volEspecialidads) {
        this.volEspecialidads = volEspecialidads;
    }
    public Set getVolActivoluntDets() {
        return this.volActivoluntDets;
    }
    
    public void setVolActivoluntDets(Set volActivoluntDets) {
        this.volActivoluntDets = volActivoluntDets;
    }
    public Set getVolConfirmacions() {
        return this.volConfirmacions;
    }
    
    public void setVolConfirmacions(Set volConfirmacions) {
        this.volConfirmacions = volConfirmacions;
    }
    public Set getVolCerificacions() {
        return this.volCerificacions;
    }
    
    public void setVolCerificacions(Set volCerificacions) {
        this.volCerificacions = volCerificacions;
    }




}


